creack/pty

run.go

If we're passed an exec.Cmd that already has a configured SysProcAttr,
Start was obliterating it by overwriting it with a new struct in order
to set `Setctty` and `Setsid`. Instead, just adjust the parameters that
we need.

run: don't override supplied SysProcAttr

---

ioctl.go
run.go
util.go

Vendoring makes it awkward to use `go test ./...` on some platforms.

Don't attempt to build on windows

---

pty_darwin.go

Prevent golang to set the non-block flag on ptmx open to avoid 100% CPU reads

---

util.go

Added terminal/pty resize functionality and utility function to inherit size from master's pty to slave. Changes type winsize to make it accessible from outside the package.

Added SetSize functionality

---

mktypes.bash
pty_openbsd.go
pty_unsupported.go
types_openbsd.go
ztypes_openbsd_amd64.go

Minor change based on #48 
Fixes the cross compile (remove "C" import from pty_openbsd.go)
Fixes ztype generation on openbsd 6.2 (Add sys/time.h include to types_openbsd.go)
Tested on openbsd 6.2 amd64
Getsize / Setsize also work.

add openbsd/amd64 support

---

ztypes_openbsd_386.go

Created file from a OpenBSD 386 installation and:
go tool cgo -godefs types_openbsd.go > ztypes_openbsd_386.go
Will resolve problems over here:
https://github.com/buildkite/agent/pull/785

Add support for OpenBSD 386.  Prevents compile errors.

---

run.go

As a continue of: https://github.com/kr/pty/pull/70 (it was required to make a fix, so I forked and recreated the Pull Request).
In my case it was required to use custom Stdout (that's why I would like to see the patch merged).

Don't set Stdin/Stdout/Stderr if already set

---

go.mod
run.go

Without this change, the controlling TTY is not set, so processes like less cannot have their stdin redirected. This was partially fixed many years ago, but it seemed the last piece of the puzzle was never put in.

Set Ctty in SysProcAttr

---

ioctl.go
ioctl_solaris.go
pty_solaris.go
pty_unsupported.go
util.go
util_solaris.go

In the absence of a unit test suite, I verified this on SmartOS (Illumos kernel, an OpenSolaris derivative) using https://github.com/yudai/gotty as a test harness, but it should also work on Oracle Solaris.

support for Solaris

---

run.go

Revert #75 but don't change the "old" behavior of `pty.Start` and `pty.StartWithSize`.
Introduce `pty.StartWithAttr` to explicitly set process attributes, which allow for pty to be created without setsid/setctty, fixing the issue faced by  [aerc](https://aerc-mail.org).
Fixes error with the new go1.15 behavior introduced in  https://go-review.googlesource.com/c/go/+/231638/ ( golang/go#29458 ).
Fixes #96 
cc @kr @ddevault @myitcv

Add StartWithAttrs to allow bypassing setsid/setctty

---

pty_darwin.go

Same as in #9, on darwin if there is no controlling terminal then opening a terminal will set that as the controlling terminal for the process which then causes a failure when setting it on the child.

Add O_NOCTTY for darwin when opening slave

---

README.md

The golang.org/x/crypto/ssh/terminal package was deprecated in favor of golang.org/x/term.
relates to https://github.com/golang/go/issues/31044 / https://github.com/golang/crypto/commit/4be66e5b658251a93e17d931a68d9c0ecba9f83a

README: replace deprecated crypto/ssh/terminal

---

mktypes.bash
pty_netbsd.go
pty_unsupported.go
types_netbsd.go
ztypes_netbsd_32bit_int.go

~I'm conscious that this uses the PTM interface, which is legacy NetBSD 6.0.  Newer versions make available the PTMX interface to find and use ptys.~
Updated to use PTMX.

Add support for NetBSD 386/amd64/arm

---

util_solaris.go

This at least allows eg https://github.com/cespare/reflex to build

Add pty.InheritSize for solaris support

---

ztypes_openbsd_32bit_int.go

I noticed this when building termshark with Go 1.17.

Fix typo in openbsd build constraint

---

winsize_unsupported.go

Hi, Thank you so much for the wonderful project!
I changed the type to `uint16`  for struct compatibility with supported one.
https://github.com/creack/pty/blob/b135084511330383e4d0adc4504cf407cab59bb0/winsize_unix.go#L12-L18
Should we move the struct to `winsize.go` instead?

Use uint16 in winsize_unsupported.go

---

doc_test.go
pty_openbsd.go

While here, add test coverage for opening the TTY from the given filename.

Provide correct pty/tty file paths on OpenBSD

---

ztypes_ppc.go

After this change i am able to compile docker for the e500v2 PowerPC CPU target.
Signed-off-by: Alex Samorukov samm@os2.kiev.ua

Add support for the 32-bit PPC Linux platform

---

.github/workflows/test.yml
io_test.go
ioctl.go

cc @sio I am reverting the nonblock PR, it causes a race on Linux, randomly blocking on read/write and randomly failing to set/get size.
Adding `-count=100` to the test consistently reproduces the issue. Using `.Fd()` fixes the issue.
I would rather keep your changes and avoid `.Fd()`, but it would need to work consistently, if you have any idea, let me know.
cc @kr if you have any ideas too.

Revert #167 to avoid race on Linux.

---

ztypes_openbsd_32bit_int.go

struct ptmget is common across all OpenBSD architectures. The current version needlessly breaks compilation on ppc64 and riscv64.

ztypes_openbsd_32bit_int.go: remove arch list
